artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/krishnaik06/datasets/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/winequality-red.zip
  unzip_dir: artifacts/data_ingestion